all:
  hosts:
    node1:
      ansible_host: 10.20.0.110
      ip: 10.20.0.110
      access_ip: 10.20.0.110
    node2:
      ansible_host: 10.20.0.111
      ip: 10.20.0.111
      access_ip: 10.20.0.111
    node3:
      ansible_host: 10.20.0.112
      ip: 10.20.0.112
      access_ip: 10.20.0.112
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
