all:
  hosts:
    node1:
      ansible_host: 10.51.21.67
      ip: 10.51.21.67
      access_ip: 10.51.21.67
    node2:
      ansible_host: 10.51.21.68
      ip: 10.51.21.68
      access_ip: 10.51.21.68
    node3:
      ansible_host: 10.51.21.69
      ip: 10.51.21.69
      access_ip: 10.51.21.69
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
